name       : lv2
version    : 1.14.0
release    : 2
source     :
    - http://lv2plug.in/spec/lv2-1.14.0.tar.bz2 : b8052683894c04efd748c81b95dd065d274d4e856c8b9e58b7c3da3db4e71d32
license    : ISC
component  : multimedia.library
summary    : Open standard for audio plugins
description: |
    LV2 is an open standard for audio plugins, used by hundreds of plugins and other project. At its core, LV2 is a simple stable interface, accompanied by extensions which add functionality to support the needs of increasingly powerful audio software.
builddeps  :
    - pkgconfig(cairo-gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sndfile)
setup      : |
    count=$(echo %JOBS% | sed -e 's/-j//')
    ./waf configure --prefix=/usr \
        --jobs=$count \
        --libdir=%libdir% \
        --lv2dir=%libdir%/lv2 \
build      : |
    ./waf build
install    : |
    ./waf install --destdir="$installdir" --prefix=/usr --libdir=%libdir%
    ./waf clean
