name       : lv2
version    : 1.18.10
release    : 5
source     :
    - git|https://github.com/lv2/lv2.git : v1.18.10
license    : ISC
component  : multimedia.library
summary    : Open standard for audio plugins
description: |
    LV2 is an open standard for audio plugins, used by hundreds of plugins and other project. At its core, LV2 is a simple stable interface, accompanied by extensions which add functionality to support the needs of increasingly powerful audio software.
builddeps  :
    - pkgconfig(cairo-gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - asciidoc
    - pygments
    - python-lxml
    - python-markdown
    - rdflib
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
