name        : lv2
version     : 1.12.0
release     : 1
source      :
    - http://lv2plug.in/spec/lv2-1.12.0.tar.bz2 : 7a4a53138f10ed997174c8bc5a8573d5f5a5d8441aaac2de6cf2178ff90658e9 
license     : ISC
component   : multimedia.library
summary     : Open standard for audio plugins
description : |
     LV2 is an open standard for audio plugins, used by hundreds of plugins and other project. At its core, LV2 is a simple stable interface, accompanied by extensions which add functionality to support the needs of increasingly powerful audio software.
builddeps   :
    - pkgconfig(cairo-gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sndfile)
setup       : |
    count=$(echo %JOBS% | sed -e 's/-j//')
    ./waf configure --prefix=/usr \
        --jobs=$count \
        --libdir=%libdir% \
        --lv2dir=%libdir%/lv2 \
build       : |
    ./waf build
install     : |
    ./waf install --destdir="$installdir" --prefix=/usr --libdir=%libdir%
    ./waf clean
