name       : lv2
version    : 1.16.0
release    : 3
source     :
    - https://github.com/drobilla/lv2/archive/v1.16.0.tar.gz : 539dc7e9b474bf0a435a2cd016cf5e29542a003976f8f12091fc9c9ceef19241
license    : ISC
component  : multimedia.library
summary    : Open standard for audio plugins
description: |
    LV2 is an open standard for audio plugins, used by hundreds of plugins and other project. At its core, LV2 is a simple stable interface, accompanied by extensions which add functionality to support the needs of increasingly powerful audio software.
builddeps  :
    - pkgconfig(cairo-gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sndfile)
setup      : |
    count=$(echo %JOBS% | sed -e 's/-j//')
    %waf_configure --jobs=$count --libdir=%libdir% --lv2dir=%libdir%/lv2
build      : |
    %waf_build
install    : |
    %waf_install
    ./waf clean